### ISSUE TITLE
ArduinoJson 5.13.1 required

### ISSUE THREAD

**Issue by KaaNee** [jp112sdl/WemosD1_HomeMatic_RFID#10]
More an advice to others than an issue.
I've to change some parts for me so i've to compile by myself.
Found out that ArduinoJson (StandardLib) Version 5.13.1 is the latest that will work.
Newer ones lead to compile errors.

Perhaps the Library Versiond should be noted, which are working.

**Comment by jp112sdl** [comment]
Thanks. 
But I've linked the working version into [libraries](https://github.com/jp112sdl/WemosD1_HomeMatic_RFID/tree/master/libraries) folder. ;)

**Comment by KaaNee** [comment]
didnt expect links of librarys in checkout-folder. So - no issue. (Just missed the versions written in manual).
