### ISSUE TITLE
Stromversorgung

### ISSUE THREAD

**Issue by Linustrispoke** [jp112sdl/WemosD1_HomeMatic_RFID#11]
Hi, nicht lachen ....
Zuerst ein großes Lob, super Anleitung und Idee, aber ...
Ich bin zwar nicht gänzlich unerfahren im Basteln und zusammenlöten solcher Bauteile, aber wo bitte wird die Stromversorgung angelötet? Laut Aufbauplan ist 5V und G nur intern verdrahtet, auf den Bildern erkenne ich es auch nicht wirklich. Beim Flashen kommt der Strom über USB (vermute ich) und im Betrieb? Auch über die USB-Buchse oder direkt auf die Platine verlöten?
Du machst dir bestimmt in die Hosen vor Lachen, aber ich stehe total auf dem Schlauch ...

**Comment by jp112sdl** [comment]
Hi,

du schließt das 5V Netzteil an den `5V`- und `GND`-Pin des Wemos an.

**Comment by Linustrispoke** [comment]
Alles klar, danke für die Erleuchtung .....
Dann werd ich mich mal dran machen.
