### ISSUE TITLE
UDP an Loxone oder FHEM

### ISSUE THREAD

**Issue by leschNUX** [jp112sdl/WemosD1_HomeMatic_RFID#12]
Hi,

Coole Idee mit dem RFID. Ich setzte fhem und loxone ein und hab kein homematic. 
Da du auch einen sonoffto loxone entworfen hast, gehe ich davon aus das du auch loxone hast.

Es wäre Super wenn du das WemosD1_HomeMatic_RFID um UDP(loxone anbindung) erweitern könntest oder um fhem(http).

Gruss

**Comment by jp112sdl** [comment]
Hi,

nein ich habe kein Loxone und entwickle an dem Projekt auch nicht mehr weiter.
SonoffHMLOX ist nur entstanden, weil ein Freund von mir Loxone einsetzt und er auch gern die Sonoff einbinden wollte.
Sorry...
