### ISSUE TITLE
Hallo

### ISSUE THREAD

**Issue by wiese-computer** [jp112sdl/WemosD1_HomeMatic_RFID#2]
Ein Tolles Projekt,
Eine kleine Anmerkung, eventuell habe ich ja was übersehen, aber die System Variable vom D1  Image "WemosD1_HomeMatic_RFID.ino.d1_mini.bin" Heist "Alarm_schaltbar" und  in der Anleitung "Alarm_scharfschaltbar". Nach Änderung in der CCU läuft alles tadellos. MfG Uwe Wiese  info@wiese-computer.de

**Comment by jp112sdl** [comment]
Hallo, 
das kann ich leider nicht nachvollziehen.

Sowohl in der [Anleitung zum Anlegen der Systemvariablen](https://github.com/jp112sdl/WemosD1_HomeMatic_RFID/wiki/HomeMatic_Systemvariablen_anlegen) als auch in der [Wemos Konfiguration](https://github.com/jp112sdl/WemosD1_HomeMatic_RFID/wiki/WemosD1_WifiManager_Config) ist der Name der Variable `Alarm_scharfschaltbar`.

Bei der Suche nach `Alarm_schaltbar` im gesamten Repository, finde ich keinen Treffer.

Auch haben andere Nachbauer, mit denen ich in Kontakt stehe, noch nie etwas zu einer falschen Variablenbezeichnung gesagt.

Ein Screenshot, auf dem zu sehen ist, wo `Alarm_schaltbar` auftaucht, würde evtl. noch Licht ins Dunkel bringen.

LG Jérôme

**Comment by wiese-computer** [comment]
![wemos1](https://user-images.githubusercontent.com/34134334/33937688-a7aa0080-e004-11e7-82b9-7a6574d14cba.jpg)
Habe den Wemos mit dem direktem Download geflasht, Bild wemos1   und der seriell port Monitor im Bild wemos2  ziemlich zum Schluss, hellrot markiert.
 
War nicht als Kritik gemeint steckt viel Arbeit von Ihnen dahinter. Beste Grüße Uwe 
 
![wemos2](https://user-images.githubusercontent.com/34134334/33937661-942acae4-e004-11e7-9af5-0e199df63c33.jpg)

**Comment by jp112sdl** [comment]
Ok, also was im seriellen Monitor zu sehen ist (mit der hellroten Markierung) ist der in der Wemos-WifiManager selbst eingegebene Wert. 
Es kann nur von der eigenen Eingabe dort kommen... Alles was zwischen den Anführungszeichen (= %22) steht, bzw. zwischen `HTTP` und `success`, sind die vom Benutzer konfigurierten Namen der Variablen, die im [WifiManager](https://github.com/jp112sdl/WemosD1_HomeMatic_RFID/wiki/WemosD1_WifiManager_Config) eingegeben werden müssen. Auch dort ist in der Beispielabbildung `Alarm_scharfschaltbar` zu sehen.

Ich sehe es nicht als Kritik. Nur wenn ein Fehler vorhanden ist, möchte ich den auch ausbügeln. ;-) 
Aber es gibt keine Stelle, an dem im Code bereits eine Variable mit `Alarm_schaltbar` vorbelegt sein könnte.

**Comment by wiese-computer** [comment]
Sorry, war die fehlerhafte Eingabe im WiFi Manager.....
Habe ich beim graueren hinsehen des Seriell Monitor während des starten auch gesehen.
Lieben Dank 

Uwe

**Comment by jp112sdl** [comment]
Passiert schon mal 👍 

Gerne, und viel Spaß mit dem Projekt!
