### ISSUE TITLE
wofür der Taster?

### ISSUE THREAD

**Issue by DiJe54** [jp112sdl/WemosD1_HomeMatic_RFID#4]
Wofür wird der Taster gebraucht?

**Comment by jp112sdl** [comment]
Zum Starten des WifiManagers / Konfigurationsmodus. 

https://github.com/jp112sdl/WemosD1_HomeMatic_RFID/wiki/WemosD1_WifiManager_Config

**Comment by DiJe54** [comment]
Danke Jerome,
hatte das teil schon am laufen.
Beim nochmaligen drüber sehen, wußte ichs nicht mehr.
Habe den nicht eingelötet, ich überbrücke den nur.
Gruß Dieter
