### ISSUE TITLE
In­te­r­es­santes Projekt!

### ISSUE THREAD

**Issue by MathiasJZ** [jp112sdl/WemosD1_HomeMatic_RFID#6]
ich würde mir den RFID-Reader gerne einbauen, wenn sich die Karten/Schlüsselanhänger nicht so leicht fälschen ließen.
Kann man das entweder mit einer Anwesenheitssteuerung oder mit einer PIN-Eingabe erweitern?
Gruß,
Mathias

**Comment by jp112sdl** [comment]
Hi.

Man sollte bedenken, dass es sich hierbei um ein Hobbyprojekt handelt und man damit keine VdS-taugliche Alarmanlage bauen kann. 
Schon gar nicht in Zusammenhang mit HomeMatic.
Außerdem halte ich die Wahrscheinlichkeit, dass jemand einen RFID Chip klont, um dieses System "zu überlisten", für sehr gering.
Wer sich die Mühe macht, um spurenlos (mit geklonter Karte) in ein Haus einzudringen, ist wohl eher auf das Erbeuten hoher Sachwerte aus. Und sofern man solche schützen möchte, bedarf es anderer Alarmanlagen.

Wie auch immer - um deine Frage zu beantworten:
Ja klar, machen kann man alles!
