### ISSUE TITLE
Long Hold Problem

### ISSUE THREAD

**Issue by Alveran81** [jp112sdl/WemosD1_HomeMatic_RFID#8]
Hallo,

gibt es einen Trick? Bekomme es nur bei einem von 30 Versuchen hin den Long Hold auszulösen und somit die Alarmanalge scharf zuschalten.

**Comment by jp112sdl** [comment]
Hi,
nein da gibt es keinen Trick. 

Aber jemand ausm *Bekanntenkreis* hatte auch mal so ein Problem. 
Ist schon ewig her.
Ich weiß gar nicht mehr, woran es lag... 
ich glaub entweder am Abstand zwischen Chip und Leser (zu dicht ist auch nicht gut!) oder sogar am RFID-Leser selbst.

**Comment by jp112sdl** [comment]
@plehr Hatten wir uns damals bei FB darüber ausgetauscht? Ist alles soooo lange her... 😄

**Comment by Alveran81** [comment]
Habe verschiedene Chips und Karten probiert. Über zwei Stunden in allen möglichen Abständen. Werde mal einen anderes Lesegerät probieren. Habe zum Glück mehre bestellt.

**Comment by plehr** [comment]
@jp112sdl Ja wir hatten uns damals darüber unterhalten... Karten funktionieren bei mir zwar auch, allerdings eher unzuverlässig. Chips sind super :)
@Alveran81 ich habe folgendes Lesegerät: MFRC522

**Comment by Alveran81** [comment]
Habe jetzt einen neue Platine angelötet. Leider immer noch genau so bescheiden. Von 30 oder 50 versuchen klappt einer. Egal ob Karte, Chip oder Systemfremde Chips von Dom. :-( 
Abstand von 0 bis 20mm mit Plastik scheiben simuliert. Ich verzweifel bald.
Lässt sich das Script vielleicht einfach ändern das er einfach toggelt (also ein und aus bei short Hold)

**Comment by jp112sdl** [comment]
Nein, so einfach nicht, weil der IST-Zustand in der CCU vorher erst geprüft werden müsste.

**Comment by Alveran81** [comment]
Dann frag ich mal ganz nett, könntest du eine solche Abfrage programmieren?

**Comment by jp112sdl** [comment]
Da muss ich dich leider enttäuschen.
Es wären größere Umbauarbeiten notwendig und die Schaltung + Code funktionieren bei vielen (eigentlich allen) Nutzern so wie sie ist, so dass es aus meiner Sicht auch sinnvoller wäre, die Ursache für die Fehlfunktion zu suchen und zu beseitigen.

Ich kann aus Zeitgründen und der Vielzahl an Projekten leider keine Individualprogrammierungen anbieten.
Sorry...

**Comment by plehr** [comment]
@Alveran81 ich habe um meinen Reader eine Art "Hülle". Damit ist der Abstand zur Platine immer ähnlich mit 1-3 cm Abstand. Dann kann der "User" den Chips an "das Lesegerät" bzw die Hülle davon drücken, der Chip wackelt nicht und eventuell steigt damit die Chance auf einen "long hold". Also: gleicher Abstand vom Chip zum Lesegerät, nicht wackeln und im Zweifel den Chip drehen. Eventuell noch die Vorder- und mal die Rückseite testen.

Viel Erfolg!

**Comment by Alveran81** [comment]
@jp112sdl. Kein Problem, trotzdem danke. 

Testtag 3.  Ich hab jetzt jeden Tag 2h versucht den richtigen Abstand zu finden. Das Problem muss wo anders liegen. Das kann ich meiner Familie so nicht präsentieren. Keiner stellt sich vor das Haus und versucht 30 mal die Alarmanalage scharf zu bekommen. 

Was könnte man noch probieren?

**Comment by Alveran81** [comment]
Nach langen probieren hab ich einen Abstand gefunden mit dem es funktioniert. Dabei kommt es auf einen halben mm an. Es funktioniert dann aber auch nur eine Sorte von Chips. Die Karten und Chips anderer Hersteller benötigen andere Abstände. (Long Hold, Short hold ist kein Problem)
Vielleicht lässt sich für die Zukunft noch eine praktikablere Lösung finden!

**Comment by jp112sdl** [comment]
@Alveran81 Ich glaub, der RDM6300 ist da toleranter.
Kostet aus China keine 2 EUR. Könntest du ja noch versuchen.

**Comment by Alveran81** [comment]
Hab bei Amazon einen bestellt. Kommt schon am Dienstag. Ich werde berichten.

**Comment by homesec24** [comment]
Hallo und vielen Dank erst einmal für Deine Arbeit und das tolle Projekt!

Ich habe mich heute auch daran versucht, leider mit den gleichen Problemen :(
Werde mir wohl eine Kartenführung aus Alu anfertigen um immer den gleichen Abstand zum Leser zu haben und hoffe, dass es dann besser geht ;)

Oder kann ich evtl. den short hold in der CCU irgendwie auswerten bzw. den long hold von der Zeit verkürzen, da ich das ganze nur als Türöffner verwenden möchte!?

**Comment by jp112sdl** [comment]
Hi,

> Oder kann ich evtl. den short hold in der CCU irgendwie auswerten

Ja, das kannst du.
Der short/long Hold macht nix anderes,als in die Systemvariable `RFID_command` einzutragen:
`0;<RFID>` = kurz oder
`1;<RFID>` = lang


Auf diese Änderung (bzw. Aktualisierung) kannst du in einem Programm reagieren, so wie es bei der RFID-Verarbeitung auch passiert: https://github.com/jp112sdl/WemosD1_HomeMatic_RFID/wiki/HomeMatic_Programm_Alarmanlage_RFID_Verarbeitung_anlegen
