### ISSUE TITLE
RDM6300

### ISSUE THREAD

**Issue by Alveran81** [jp112sdl/WemosD1_HomeMatic_RFID#9]
Hallo,
habe jetzt endlich meine RDM6300 erhalten. 
Leider will es nicht so richtig klappen. 
Laut Zeichung wird außer plus und minus nur ein Kabel verbunden, kann das so richtig sein?
https://github.com/jp112sdl/WemosD1_HomeMatic_RFID/wiki/Zusammenbau

Ist es möglich das andere Tags benötigt werden als beim MFRC522?

**Comment by jp112sdl** [comment]
Hi,

> Laut Zeichung wird außer plus und minus nur ein Kabel verbunden, kann das so richtig sein?

Ja das ist richtig so. Der RDM sendet die Daten seriell.


> Ist es möglich das andere Tags benötigt werden als beim MFRC522?

Ja, der benötigt andere.
MFRC = 13.56MHz Transponder
RDM = 125kHz Transponder

**Comment by Alveran81** [comment]
OK vielen Dank.

Dann werde ich mal welche bestellen.

**Comment by jp112sdl** [comment]
> Bitte tut allen Usern den gefallen und streicht den MFRC von den Anleitungen.

Natürlich nicht!
Von allen Nachbauten, _von denen ich weiß (lass es so ca. 10 sein)_, gabs bisher bei zweien Probleme.

**Comment by Alveran81** [comment]
Entschuldigung. Ich dachte es ist ein generelles Problem. Vielleicht handelt es sich bei meiner Bestellung um eine schlechte Produktionsserie.
Ich habe drei MFRC und alle haben das gleiche Problem.

**Comment by jp112sdl** [comment]
Hehe, das Problem ist halt, dass der RDM für ein künftiges AskSinPP Projekt ungeeignet ist.
Da wirds dann zwangsweise auf den MFRC hinaus laufen.

Aber hier gehts erstmal mit dem RDM 👍

**Comment by Alveran81** [comment]
Ich denke ich weiß was du vorhast. Darf ich es hier schreiben?

**Comment by jp112sdl** [comment]
Ich weiß selbst noch nicht konkret, was ich vor hab 🤣 
Aber schreib mal was du denkst

**Comment by Alveran81** [comment]
RFID mit arduino pro mini und cc1101.
